### ISSUE TITLE
feat(zsh): neovim script rewrite

### ISSUE THREAD

**Issue by peter-bread** [peter-bread/.dotfiles#12]
# Rewrite neovim cli script

The overall goal of this is to use a config file so settings persist across shells and it might make shell completion better if it can read the list of registered configs.

## Definite

- [ ] use YAML config file

```yaml
current: peter.nvim

configs:
  peter.nvim:
    desc: My personal config

  minimal.nvim:
    desc: Minimal config

  lazyvim:
    desc: LazyVim distro
```

- [ ] new function `neovim add <name>` to register neovim configs
- [ ] new function `neovim remove <name>` to unregister neovim configs

## Maybe

- [ ] add `dependencies` field to each config (e.g. a they might require `rg`, `fd` for telescope, or `cargo` for a certain tool from Mason
- [ ] modify certain functions:
  - right now they all assume i am using the lazy plugin manager
